### ISSUE TITLE
provide versioned binaries on nexus

### ISSUE THREAD

**Issue by erickeller** [LieberLieber/LemonTree.Pipeline.Tools#13]
currently we can integrate this tool with the latest available version.
Yet for reproducibility it would be preferable to use some semantic versioning of the tool and be able to grab a specific version in the CI/CD.

from `https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/LemonTree.Pipeline.Tools.ModelCheck.exe`
to `https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/v1.0.0/LemonTree.Pipeline.Tools.ModelCheck.exe`

also consider to deploy a latest version following the main branch to:
`https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/latest/LemonTree.Pipeline.Tools.ModelCheck.exe`

this can be useful for continuous integration of latest version to test bleeding edge fixes or features.

**Comment by danielsiegl** [comment]
@erickeller sorry it took a while - but I think time is right to do that now!

**Comment by danielsiegl** [comment]
The Plan:
* Versions from Tag go to: https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/LemonTree.Pipeline.Tools.ModelCheck.exe
* And for history reasons to: https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/v1.0.0/LemonTree.Pipeline.Tools.ModelCheck.exe
*  The latest build from main will be deployed to https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/latest/LemonTree.Pipeline.Tools.ModelCheck.exe

**Comment by danielsiegl** [comment]
Tried to make modular workflows to control build trigger nicely
https://github.com/danielsiegl/reusableworkflows/tree/main/.github/workflows

**Comment by danielsiegl** [comment]
Automatically Attaching the binaries to a release doesn't work the rest is done.
