### ISSUE TITLE
Update projects to net6.0

### ISSUE THREAD

**Issue by aschoelzhorn** [LieberLieber/LemonTree.Pipeline.Tools#41]
* Update all projects to net6.0 (executables) and multi target libraries (net6.0, netstandard2.0)
* Replace ILMerge with dotnet technologie (pusblish as single exe)

**Comment by aschoelzhorn** [comment]
depends on #40

**Comment by danielsiegl** [comment]
Would be nice if we can also build a 32bit Windows Version to support .eapx going forward.

**Comment by danielsiegl** [comment]
We should also have a github action that runs on ubuntu to validate it's working.
