### ISSUE TITLE
Imlement LemonTree readiness pipeline tool

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Pipeline.Tools#8]
- [x] Check how much space compact can reduce - warn if it is more than 25% Error on 50% or something like that
- [x] Check for Baseline
- [x] Check if User Security is enabled
- [x] Check for Diagram Image Maps
- [x] Check for other Binaries
- [ ] Report on Profile in Model
- [x] Check for audit entries (in t_snapshot)
- [x] Check if Audit is turned on
- [x] Check for t_image entries
- [x] Check for "Modeldocuments"
- [x] Check for ExtDoc - embedded binaries
- [x] Check for Version Controlled Packages (similar as User Security, but it's locked differently in the DB)
- [x] Create output.md
- [x] Set Exitcode so the build scripts can decide when it would fail
- [x] Integrate in Build.yml to test it in build environment
- [x] Include Upload to Nexus in Build Script.
- [x] Post output.md in Pullrequest
- [ ] if git check for LFS on that filetype
- [x] Clean up build.yml once it is done.
- [x] Report possible size reduction if all the unwanted stuff is deleted before compact.
- [x] Work on review comments
- [x] --NoCompact to disable compact of the databases checks

Report should be output to .md so it can be used in comments and such.

**Comment by danielsiegl** [comment]
@philippkalenda do you have more Ideas?

**Comment by philippkalenda** [comment]
- [ ] Check for audit entries (in t_snapshot)
- [ ] Check for Version Controlled Packages (similar as User Security, but it's locked differently in the DB)
- [ ] Check for Inconsistencies (to have a clean start when introducing this model to VCS)

**Comment by danielsiegl** [comment]
Some More Info: 
•	check also, if the auditing feature is enabled. If it is enabled, you will have audit logs over and over again and the audit log entry check will always report an issue.
Is found here in the t_genopt:
reveng=0;xmiimport=0;xmiexport=0;enabled=1;auditLevel=131072;auditOptions=4;dbtimestamp=0;
•	it's more a recommendation or a warning:
if the t_document contains "ModelDocuments" or the t_image contains entries, we could display a suggestion to remove binary content in order to keep the model as small as possible
